/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as stationContractSol from "./StationContract.sol";
export { IStation__factory } from "./IStation__factory";
