/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stationContractSol from "./StationContract.sol";
export type { stationContractSol };
export type { IStation } from "./IStation";
